#!/bin/zsh
# Correct the shebang if required

OLD_MUNKI_PYTHON="\/usr\/local\/munki\/python"
MUNKI_PYTHON="\/usr\/local\/munki\/munki-python"
CONDITIONS=/usr/local/munki/conditions

if [[ -L /usr/local/munki/munki-python ]]; then
    for f in ${CONDITIONS}/com.github.carlashley.*.py; do
        /usr/bin/sed -i '' "s/${OLD_MUNKI_PYTHON}/${MUNKI_PYTHON}/g" ${f}
    done
fi
